# ✅ AndroidX
android.useAndroidX=true
android.enableJetifier=false
android.suppressUnsupportedCompileSdk=34

# ⚡ COMPILATION — OPTIONS COMPATIBLES Java 17 + Gradle 8.2
org.gradle.jvmargs=-Xmx3072m -Xms1024m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.daemon=false
org.gradle.workers.max=6

kotlin.incremental=true
kotlin.caching.enabled=true

# 📦 APK ALLÉGÉ
android.enableR8.fullMode=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=false
android.defaults.buildfeatures.aidl=false
android.defaults.buildfeatures.renderscript=false
