#!/bin/sh
##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

APP_HOME=$( cd "$( dirname "$0" )" && pwd )

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ -z "$JAVA_HOME" ] ; then
    JAVA_EXECUTABLE=java
else
    JAVA_EXECUTABLE=$JAVA_HOME/bin/java
fi

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command:
GRADLE_ARGS="$DEFAULT_JVM_OPTS"
for arg in "$@"; do
    GRADLE_ARGS="$GRADLE_ARGS $arg"
done

exec "$JAVA_EXECUTABLE" -classpath "$CLASSPATH" \
    "-Dorg.gradle.appname=$(basename "$0")" \
    org.gradle.wrapper.GradleWrapperMain "$@"
